# Generated by Django 6.0.4 on 2026-04-30 22:53

import core.validators
import django.core.validators
import django.db.models.functions.text
import django_countries.fields
import djmoney.models.fields
import timezone_field.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid7, editable=False, unique=True)),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('slug', models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(message='Slug must contain only lowercase letters, digits, and hyphens.', regex='^[a-z0-9-]+$')], verbose_name='slug')),
                ('country', django_countries.fields.CountryField(default='BE', max_length=2, verbose_name='country')),
                ('default_timezone', timezone_field.fields.TimeZoneField(default='Europe/Brussels', verbose_name='default timezone')),
                ('default_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('GBP', 'GBP £'), ('JPY', 'JPY ¥'), ('USD', 'USD $')], default='EUR', max_length=3, validators=[core.validators.validate_currency], verbose_name='default currency')),
                ('default_language', models.CharField(choices=[('en-US', 'English'), ('nl-BE', 'Nederlands'), ('fr-BE', 'Français'), ('de-DE', 'Deutsch')], default='en-US', max_length=8, verbose_name='default language')),
                ('vat_number', models.CharField(max_length=14, verbose_name='VAT number')),
                ('billing_email', models.EmailField(max_length=254, verbose_name='billing email')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid7, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('preferred_language', models.CharField(blank=True, choices=[('en-US', 'English'), ('nl-BE', 'Nederlands'), ('fr-BE', 'Français'), ('de-DE', 'Deutsch')], max_length=8, verbose_name='preferred language')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['email'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='user_email_ci_unique')],
            },
        ),
    ]
