# Generated by Django 6.0.4 on 2026-04-30 22:23

import core.validators
import django.core.validators
import django_countries.fields
import djmoney.models.fields
import timezone_field.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid7, editable=False, unique=True)),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('slug', models.SlugField(unique=True, validators=[django.core.validators.RegexValidator(message='Slug must contain only lowercase letters, digits, and hyphens.', regex='^[a-z0-9-]+$')], verbose_name='slug')),
                ('country', django_countries.fields.CountryField(default='BE', max_length=2, verbose_name='country')),
                ('default_timezone', timezone_field.fields.TimeZoneField(default='Europe/Brussels', verbose_name='default timezone')),
                ('default_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('GBP', 'GBP £'), ('JPY', 'JPY ¥'), ('USD', 'USD $')], default='EUR', max_length=3, validators=[core.validators.validate_currency], verbose_name='default currency')),
                ('default_language', models.CharField(choices=[('en-US', 'English'), ('nl-BE', 'Nederlands'), ('fr-BE', 'Français'), ('de-DE', 'Deutsch')], default='en-US', max_length=8, verbose_name='default language')),
                ('vat_number', models.CharField(max_length=14, verbose_name='VAT number')),
                ('billing_email', models.EmailField(max_length=254, verbose_name='billing email')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
