# Generated by Django 6.0.4 on 2026-04-30 23:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_organizationmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.UUIDField(default=uuid.uuid7, editable=False, unique=True)),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('slug', models.SlugField(validators=[django.core.validators.RegexValidator(message='Slug must contain only lowercase letters, digits, and hyphens.', regex='^[a-z0-9-]+$')], verbose_name='slug')),
                ('street', models.CharField(max_length=200, verbose_name='street')),
                ('postal_code', models.CharField(max_length=16, verbose_name='postal code')),
                ('city', models.CharField(max_length=120, verbose_name='city')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='phone')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='core.organization', verbose_name='organization')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
                'ordering': ['organization', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pin', models.CharField(blank=True, max_length=128, verbose_name='PIN')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_memberships', to='core.location', verbose_name='location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_memberships', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'location membership',
                'verbose_name_plural': 'location memberships',
                'ordering': ['location', 'user'],
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='location_org_slug_unique'),
        ),
        migrations.AddConstraint(
            model_name='locationmembership',
            constraint=models.UniqueConstraint(fields=('user', 'location'), name='locmembership_user_location_unique'),
        ),
    ]
