# Generated by Django 6.0.4 on 2026-05-02 22:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.SlugField(help_text='Used in web addresses for this location.', validators=[django.core.validators.RegexValidator(message='URL must contain only lowercase letters, digits, and hyphens.', regex='^[a-z0-9-]+$')], verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(help_text='Used in web addresses, e.g. /o/your-url/.', unique=True, validators=[django.core.validators.RegexValidator(message='URL must contain only lowercase letters, digits, and hyphens.', regex='^[a-z0-9-]+$')], verbose_name='URL'),
        ),
    ]
